replicaCount: 1

image:
  repository: noletengine/python-app
  tag: 508cdc9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: apps.srespace.tech
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: python-app-tls
      hosts:
        - apps.srespace.tech

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

ingress:
  enabled: true
  host: apps.srespace.tech
  tlsSecret: python-app-tls
