name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ allow workflow to push commits back to the repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: noletengine/python-app:${{ env.TAG }}

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag: .*/tag: ${{ env.TAG }}/" python-app/values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add python-app/values.yaml
          git commit -m "Update image tag to ${{ env.TAG }}" || echo "No changes to commit"
          git push origin main || true
